raw_columns:
  target:
    - Churn
  categorical:
    - gender
    - Partner
    - Dependents
    - PhoneService
    - MultipleLines
    - InternetService
    - OnlineSecurity
    - OnlineBackup
    - DeviceProtection
    - TechSupport
    - StreamingTV
    - StreamingMovies
    - Contract
    - PaperlessBilling
    - PaymentMethod
  numerical:
    - SeniorCitizen
    - tenure
    - MonthlyCharges
    - TotalCharges

columns:
  target:
    - Churn
  categorical:
    - gender
    - Partner
    - Dependents
    - PhoneService
    - MultipleLines
    - InternetService
    - OnlineSecurity
    - OnlineBackup
    - DeviceProtection
    - TechSupport
    - StreamingTV
    - StreamingMovies
    - Contract
    - PaperlessBilling
    - PaymentMethod
  numerical:
    - SeniorCitizen
    - tenure
    - MonthlyCharges
    - TotalCharges
    - avg_charge_per_month

split_ratio:
  train: 0.7
  validation: 0.15
  test: 0.15

random_state: 42

stratify_column: Churn

fit_transform:
  split_to_fit:
    - train
